In [ ]:
import polars as pl

In [2]:
df = pl.read_parquet("../data/parquet/*.parquet")
df

shape: (50_000, 5)
┌───────────┬───────────┬────────┬────────────────────────────────┬────────────────────────────────┐
│ white_elo ┆ black_elo ┆ result ┆ moves                          ┆ opening                        │
│ ---       ┆ ---       ┆ ---    ┆ ---                            ┆ ---                            │
│ i32       ┆ i32       ┆ i8     ┆ str                            ┆ str                            │
╞═══════════╪═══════════╪════════╪════════════════════════════════╪════════════════════════════════╡
│ 2071      ┆ 2030      ┆ 1      ┆ e2e4 e7e5 g1f3 d7d6 d2d4 e5d4  ┆ Philidor Defense: Exchange     │
│           ┆           ┆        ┆ …                              ┆ Var…                           │
│ 2098      ┆ 2152      ┆ 1      ┆ e2e4 e7e5 g1f3 g8f6 b1c3 b8c6  ┆ Four Knights Game: Scotch      │
│           ┆           ┆        ┆ …                              ┆ Vari…                          │
│ 2080      ┆ 2180      ┆ -1     ┆ e2e4 e7e5 g1f3 g8f6 b1c3 f8b4  ┆ Russian Game: Three Knights    │
│           ┆           ┆        ┆ …                              ┆ Ga…                            │
│ 2072      ┆ 2067      ┆ 1      ┆ e2e4 c7c5 g1f3 d7d6 d2d4 c5d4  ┆ Sicilian Defense: Najdorf      │
│           ┆           ┆        ┆ …                              ┆ Vari…                          │
│ 2091      ┆ 2001      ┆ -1     ┆ g2g4 d7d5 f1g2 c7c6 h2h3 e7e5  ┆ Grob Opening: Keene Defense    │
│           ┆           ┆        ┆ …                              ┆                                │
│ …         ┆ …         ┆ …      ┆ …                              ┆ …                              │
│ 2131      ┆ 2133      ┆ -1     ┆ e2e4 c7c5 g1f3 e7e6 d2d4 c5d4  ┆ Sicilian Defense: Kan          │
│           ┆           ┆        ┆ …                              ┆ Variatio…                      │
│ 2171      ┆ 2112      ┆ 1      ┆ e2e4 g7g6 d2d4 f8g7 b1c3 a7a6  ┆ Modern Defense: Standard Line  │
│           ┆           ┆        ┆ …                              ┆                                │
│ 2072      ┆ 2290      ┆ 1      ┆ g1f3 g7g6 d2d4 f8g7 c2c4 b7b6  ┆ Zukertort Opening: Kingside    │
│           ┆           ┆        ┆ …                              ┆ Fi…                            │
│ 2175      ┆ 2227      ┆ -1     ┆ e2e4 d7d6 d2d4 g8f6 b1c3 b8d7  ┆ Lion Defense: Anti-Philidor,   │
│           ┆           ┆        ┆ …                              ┆ L…                             │
│ 2232      ┆ 2115      ┆ -1     ┆ g2g3 c7c5 f1g2 g8f6 d2d3 b8c6  ┆ Hungarian Opening: Sicilian    │
│           ┆           ┆        ┆ …                              ┆ In…                            │
└───────────┴───────────┴────────┴────────────────────────────────┴────────────────────────────────┘

In [3]:
# opening is whatever is before :, before , and without any #2, #3, etc. suffixes
# normalize whitespace so e.g. 'Vienna Game' and 'Vienna Game ' dedupe correctly
openings = (
    df["opening"]
    .str.split(":")
    .list.get(0)
    .str.split(",")
    .list.get(0)
    .str.replace(r"#\d+", "")
    .str.strip_chars()
    .str.replace_all(r"\s+", " ")
    .unique()
    .sort()
)

for opening in openings:
    print(opening)

Alekhine Defense
Amar Opening
Amazon Attack
Anderssen Opening
Anderssen's Opening
Australian Defense
Barnes Defense
Barnes Opening
Benko Gambit
Benko Gambit Accepted
Benko Gambit Declined
Benoni Defense
Bird Opening
Bishop's Opening
Blackmar-Diemer Gambit
Blackmar-Diemer Gambit Accepted
Blackmar-Diemer Gambit Declined
Blumenfeld Countergambit
Blumenfeld Countergambit Accepted
Bogo-Indian Defense
Borg Defense
Budapest Defense
Canard Opening
Caro-Kann Defense
Carr Defense
Catalan Opening
Center Game
Center Game Accepted
Clemenz Opening
Colle System
Czech Defense
Danish Gambit
Danish Gambit Accepted
Danish Gambit Declined
Duras Gambit
Dutch Defense
East Indian Defense
Elephant Gambit
English Defense
English Opening
English Orangutan
Englund Gambit
Englund Gambit Complex
Englund Gambit Complex Declined
Englund Gambit Declined
Four Knights
Four Knights Game
Franco-Benoni Defense
French Defense
Gedult's Opening
Giuoco Piano
Goldsmith Defense
Grob Opening
Gruenfeld Defense
Grünfeld Defense
Guatemala Defense
Gunderam Defense
Hippopotamus Defense
Horwitz Defense
Hungarian Opening
Indian Defense
Indian Game
Italian Game
Kadas Opening
Kangaroo Defense
King's Gambit
King's Gambit Accepted
King's Gambit Declined
King's Indian
King's Indian Attack
King's Indian Defense
King's Knight Opening
King's Pawn
King's Pawn Game
King's Pawn Opening
Kádas Opening
Lasker Simul Special
Latvian Gambit
Latvian Gambit Accepted
Lion Defense
London System
Marienbad System
Mexican Defense
Mieses Opening
Mikenas Defense
Modern Defense
Montevideo Defense
Neo-Gruenfeld Defense
Neo-Grünfeld Defense
Nimzo-Indian Defense
Nimzo-Larsen Attack
Nimzowitsch Defense
Nimzowitsch-Larsen Attack
Old Benoni Defense
Old Indian
Old Indian Defense
Owen Defense
Paleface Attack
Petrov
Petrov's Defense
Philidor Defense
Pirc Defense
Polish Defense
Polish Opening
Ponziani Opening
Portuguese Opening
Pseudo Queen's Indian Defense
Pterodactyl Defense
Queen's Gambit
Queen's Gambit Accepted
Queen's Gambit Declined
Queen's Gambit Refused
Queen's Indian Accelerated
Queen's Indian Defense
Queen's Pawn
Queen's Pawn Game
Queen's Pawn Opening
Rapport-Jobava System
Rat Defense
Reti Opening
Richter-Veresov Attack
Robatsch (Modern) Defense
Robatsch Defense
Rubinstein Opening
Russian Game
Ruy Lopez
Réti Opening
Saragossa Opening
Scandinavian Defense
Scotch Gambit
Scotch Game
Semi-Benoni
Semi-Bononi
Semi-Slav Defense
Semi-Slav Defense Accepted
Sicilian Defense
Slav Defense
Slav Indian
Sodium Attack
St. George Defense
System
Tarrasch Defense
Three Knights Opening
Torre Attack
Trompowsky Attack
Valencia Opening
Van Geet Opening
Van't Kruijs Opening
Vienna Gambit
Vienna Game
Vulture Defense
Wade Defense
Ware Defense
Ware Opening
Yusupov-Rubinstein System
Zukertort Opening

In [4]:
moves = df[0]["moves"].to_list()[0]
print(moves)

e2e4 e7e5 g1f3 d7d6 d2d4 e5d4 f3d4 f8e7 f1c4 g8f6 b1c3 e8g8 e1g1 a7a6 a2a3 c7c5 d4e2 b8c6 f2f4 c8g4 d1e1 b7b5 c4d5 f6d5 c3d5 c6d4 e2d4 c5d4 f4f5 f7f6 c1f4 a8c8 e1d2 g4h5 a1c1 h5f7 d2d4 c8c4 d4d3 f7d5 d3d5 g8h8 c2c3 d8b6 g1h1 a6a5 c1d1 c4c6 d5e6 b5b4 e6e7 f8d8 c3b4 a5b4 a3b4 h7h6 b4b5 c6c8 d1d6 d8d6 f4d6 b6b5 f1e1 c8e8 e7c7 e8e4 e1c1 b5f5 h2h3 e4e2 b2b4 f5f2 c7c8 h8h7 c8g4 e2b2 d6c5 f2d2 c1d1 d2c2 d1e1 f6f5 g4g3

In [5]:
moves = df["moves"].str.split(" ")
moves

shape: (50_000,)
Series: 'moves' [list[str]]
[
	["e2e4", "e7e5", … "g4g3"]
	["e2e4", "e7e5", … "e5d6"]
	["e2e4", "e7e5", … "c2g2"]
	["e2e4", "c7c5", … "e1e4"]
	["g2g4", "d7d5", … "f2f1"]
	…
	["e2e4", "c7c5", … "g5b5"]
	["e2e4", "g7g6", … "d3g6"]
	["g1f3", "g7g6", … "f7d7"]
	["e2e4", "d7d6", … "e5f4"]
	["g2g3", "c7c5", … "b7b3"]
]

In [6]:
all_moves = moves.explode().unique().sort()  # just experimenting, they are not all possible moves
all_moves

shape: (1_910,)
Series: 'moves' [str]
[
	"a1a2"
	"a1a3"
	"a1a4"
	"a1a5"
	"a1a6"
	…
	"h8h3"
	"h8h4"
	"h8h5"
	"h8h6"
	"h8h7"
]

In [7]:
with open("../data/all_uci_moves.txt") as f:
    all_uci_moves = [line.strip() for line in f]

all_uci_moves

['a1h8',
 'a1a8',
 'a1g7',
 'a1a7',
 'a1f6',
 'a1a6',
 'a1e5',
 'a1a5',
 'a1d4',
 'a1a4',
 'a1c3',
 'a1a3',
 'a1b2',
 'a1a2',
 'a1h1',
 'a1g1',
 'a1f1',
 'a1e1',
 'a1d1',
 'a1c1',
 'a1b1',
 'a2g8',
 'a2a8',
 'a2f7',
 'a2a7',
 'a2e6',
 'a2a6',
 'a2d5',
 'a2a5',
 'a2c4',
 'a2a4',
 'a2b3',
 'a2a3',
 'a2h2',
 'a2g2',
 'a2f2',
 'a2e2',
 'a2d2',
 'a2c2',
 'a2b2',
 'a2b1',
 'a2a1',
 'a3f8',
 'a3a8',
 'a3e7',
 'a3a7',
 'a3d6',
 'a3a6',
 'a3c5',
 'a3a5',
 'a3b4',
 'a3a4',
 'a3h3',
 'a3g3',
 'a3f3',
 'a3e3',
 'a3d3',
 'a3c3',
 'a3b3',
 'a3b2',
 'a3a2',
 'a3c1',
 'a3a1',
 'a4e8',
 'a4a8',
 'a4d7',
 'a4a7',
 'a4c6',
 'a4a6',
 'a4b5',
 'a4a5',
 'a4h4',
 'a4g4',
 'a4f4',
 'a4e4',
 'a4d4',
 'a4c4',
 'a4b4',
 'a4b3',
 'a4a3',
 'a4c2',
 'a4a2',
 'a4d1',
 'a4a1',
 'a5d8',
 'a5a8',
 'a5c7',
 'a5a7',
 'a5b6',
 'a5a6',
 'a5h5',
 'a5g5',
 'a5f5',
 'a5e5',
 'a5d5',
 'a5c5',
 'a5b5',
 'a5b4',
 'a5a4',
 'a5c3',
 'a5a3',
 'a5d2',
 'a5a2',
 'a5e1',
 'a5a1',
 'a6c8',
 'a6a8',
 'a6b7',
 'a6a7',
 'a6h6',
 'a6g6',
 'a6f6',
 'a6e6',
 'a6d6',
 'a6c6',
 'a6b6',
 'a6b5',
 'a6a5',
 'a6c4',
 'a6a4',
 'a6d3',
 'a6a3',
 'a6e2',
 'a6a2',
 'a6f1',
 'a6a1',
 'a7b8',
 'a7a8',
 'a7h7',
 'a7g7',
 'a7f7',
 'a7e7',
 'a7d7',
 'a7c7',
 'a7b7',
 'a7b6',
 'a7a6',
 'a7c5',
 'a7a5',
 'a7d4',
 'a7a4',
 'a7e3',
 'a7a3',
 'a7f2',
 'a7a2',
 'a7g1',
 'a7a1',
 'a8h8',
 'a8g8',
 'a8f8',
 'a8e8',
 'a8d8',
 'a8c8',
 'a8b8',
 'a8b7',
 'a8a7',
 'a8c6',
 'a8a6',
 'a8d5',
 'a8a5',
 'a8e4',
 'a8a4',
 'a8f3',
 'a8a3',
 'a8g2',
 'a8a2',
 'a8h1',
 'a8a1',
 'b1b8',
 'b1h7',
 'b1b7',
 'b1g6',
 'b1b6',
 'b1f5',
 'b1b5',
 'b1e4',
 'b1b4',
 'b1d3',
 'b1b3',
 'b1c2',
 'b1b2',
 'b1a2',
 'b1h1',
 'b1g1',
 'b1f1',
 'b1e1',
 'b1d1',
 'b1c1',
 'b1a1',
 'b2h8',
 'b2b8',
 'b2g7',
 'b2b7',
 'b2f6',
 'b2b6',
 'b2e5',
 'b2b5',
 'b2d4',
 'b2b4',
 'b2c3',
 'b2b3',
 'b2a3',
 'b2h2',
 'b2g2',
 'b2f2',
 'b2e2',
 'b2d2',
 'b2c2',
 'b2a2',
 'b2c1',
 'b2b1',
 'b2a1',
 'b3g8',
 'b3b8',
 'b3f7',
 'b3b7',
 'b3e6',
 'b3b6',
 'b3d5',
 'b3b5',
 'b3c4',
 'b3b4',
 'b3a4',
 'b3h3',
 'b3g3',
 'b3f3',
 'b3e3',
 'b3d3',
 'b3c3',
 'b3a3',
 'b3c2',
 'b3b2',
 'b3a2',
 'b3d1',
 'b3b1',
 'b4f8',
 'b4b8',
 'b4e7',
 'b4b7',
 'b4d6',
 'b4b6',
 'b4c5',
 'b4b5',
 'b4a5',
 'b4h4',
 'b4g4',
 'b4f4',
 'b4e4',
 'b4d4',
 'b4c4',
 'b4a4',
 'b4c3',
 'b4b3',
 'b4a3',
 'b4d2',
 'b4b2',
 'b4e1',
 'b4b1',
 'b5e8',
 'b5b8',
 'b5d7',
 'b5b7',
 'b5c6',
 'b5b6',
 'b5a6',
 'b5h5',
 'b5g5',
 'b5f5',
 'b5e5',
 'b5d5',
 'b5c5',
 'b5a5',
 'b5c4',
 'b5b4',
 'b5a4',
 'b5d3',
 'b5b3',
 'b5e2',
 'b5b2',
 'b5f1',
 'b5b1',
 'b6d8',
 'b6b8',
 'b6c7',
 'b6b7',
 'b6a7',
 'b6h6',
 'b6g6',
 'b6f6',
 'b6e6',
 'b6d6',
 'b6c6',
 'b6a6',
 'b6c5',
 'b6b5',
 'b6a5',
 'b6d4',
 'b6b4',
 'b6e3',
 'b6b3',
 'b6f2',
 'b6b2',
 'b6g1',
 'b6b1',
 'b7c8',
 'b7b8',
 'b7a8',
 'b7h7',
 'b7g7',
 'b7f7',
 'b7e7',
 'b7d7',
 'b7c7',
 'b7a7',
 'b7c6',
 'b7b6',
 'b7a6',
 'b7d5',
 'b7b5',
 'b7e4',
 'b7b4',
 'b7f3',
 'b7b3',
 'b7g2',
 'b7b2',
 'b7h1',
 'b7b1',
 'b8h8',
 'b8g8',
 'b8f8',
 'b8e8',
 'b8d8',
 'b8c8',
 'b8a8',
 'b8c7',
 'b8b7',
 'b8a7',
 'b8d6',
 'b8b6',
 'b8e5',
 'b8b5',
 'b8f4',
 'b8b4',
 'b8g3',
 'b8b3',
 'b8h2',
 'b8b2',
 'b8b1',
 'c1c8',
 'c1c7',
 'c1h6',
 'c1c6',
 'c1g5',
 'c1c5',
 'c1f4',
 'c1c4',
 'c1e3',
 'c1c3',
 'c1a3',
 'c1d2',
 'c1c2',
 'c1b2',
 'c1h1',
 'c1g1',
 'c1f1',
 'c1e1',
 'c1d1',
 'c1b1',
 'c1a1',
 'c2c8',
 'c2h7',
 'c2c7',
 'c2g6',
 'c2c6',
 'c2f5',
 'c2c5',
 'c2e4',
 'c2c4',
 'c2a4',
 'c2d3',
 'c2c3',
 'c2b3',
 'c2h2',
 'c2g2',
 'c2f2',
 'c2e2',
 'c2d2',
 'c2b2',
 'c2a2',
 'c2d1',
 'c2c1',
 'c2b1',
 'c3h8',
 'c3c8',
 'c3g7',
 'c3c7',
 'c3f6',
 'c3c6',
 'c3e5',
 'c3c5',
 'c3a5',
 'c3d4',
 'c3c4',
 'c3b4',
 'c3h3',
 'c3g3',
 'c3f3',
 'c3e3',
 'c3d3',
 'c3b3',
 'c3a3',
 'c3d2',
 'c3c2',
 'c3b2',
 'c3e1',
 'c3c1',
 'c3a1',
 'c4g8',
 'c4c8',
 'c4f7',
 'c4c7',
 'c4e6',
 'c4c6',
 'c4a6',
 'c4d5',
 'c4c5',
 'c4b5',
 'c4h4',
 'c4g4',
 'c4f4',
 'c4e4',
 'c4d4',
 'c4b4',
 'c4a4',
 'c4d3',
 'c4c3',
 'c4b3',
 'c4e2',
 'c4c2',
 'c4a2',
 'c4f1',
 'c4c1',
 'c5f8',
 'c5c8',
 'c5e7',
 'c5c7',
 'c5a7',
 'c5d6',
 'c5c6',
 'c5b6',
 'c5h5',
 'c5g5',
 'c5f5',
 'c5e5',
 'c5d5',
 'c5b5',
 'c5a5',
 'c5d4',
 'c5c4',
 'c5b4',
 'c5e3',
 'c5c3',
 'c5a3',
 'c5f2',
 'c5c2',
 'c5g1',
 'c5c1',
 'c6e8',
 'c6c8',
 'c6a8',
 'c6d7',
 'c6c7',
 'c6b7',
 'c6h6',
 'c6g6',
 'c6f6',
 'c6e6',
 'c6d6',
 'c6b6',
 'c6a6',
 'c6d5',
 'c6c5',
 'c6b5',
 'c6e4',
 'c6c4',
 'c6a4',
 'c6f3',
 'c6c3',
 'c6g2',
 'c6c2',
 'c6h1',
 'c6c1',
 'c7d8',
 'c7c8',
 'c7b8',
 'c7h7',
 'c7g7',
 'c7f7',
 'c7e7',
 'c7d7',
 'c7b7',
 'c7a7',
 'c7d6',
 'c7c6',
 'c7b6',
 'c7e5',
 'c7c5',
 'c7a5',
 'c7f4',
 'c7c4',
 'c7g3',
 'c7c3',
 'c7h2',
 'c7c2',
 'c7c1',
 'c8h8',
 'c8g8',
 'c8f8',
 'c8e8',
 'c8d8',
 'c8b8',
 'c8a8',
 'c8d7',
 'c8c7',
 'c8b7',
 'c8e6',
 'c8c6',
 'c8a6',
 'c8f5',
 'c8c5',
 'c8g4',
 'c8c4',
 'c8h3',
 'c8c3',
 'c8c2',
 'c8c1',
 'd1d8',
 'd1d7',
 'd1d6',
 'd1h5',
 'd1d5',
 'd1g4',
 'd1d4',
 'd1a4',
 'd1f3',
 'd1d3',
 'd1b3',
 'd1e2',
 'd1d2',
 'd1c2',
 'd1h1',
 'd1g1',
 'd1f1',
 'd1e1',
 'd1c1',
 'd1b1',
 'd1a1',
 'd2d8',
 'd2d7',
 'd2h6',
 'd2d6',
 'd2g5',
 'd2d5',
 'd2a5',
 'd2f4',
 'd2d4',
 'd2b4',
 'd2e3',
 'd2d3',
 'd2c3',
 'd2h2',
 'd2g2',
 'd2f2',
 'd2e2',
 'd2c2',
 'd2b2',
 'd2a2',
 'd2e1',
 'd2d1',
 'd2c1',
 'd3d8',
 'd3h7',
 'd3d7',
 'd3g6',
 'd3d6',
 'd3a6',
 'd3f5',
 'd3d5',
 'd3b5',
 'd3e4',
 'd3d4',
 'd3c4',
 'd3h3',
 'd3g3',
 'd3f3',
 'd3e3',
 'd3c3',
 'd3b3',
 'd3a3',
 'd3e2',
 'd3d2',
 'd3c2',
 'd3f1',
 'd3d1',
 'd3b1',
 'd4h8',
 'd4d8',
 'd4g7',
 'd4d7',
 'd4a7',
 'd4f6',
 'd4d6',
 'd4b6',
 'd4e5',
 'd4d5',
 'd4c5',
 'd4h4',
 'd4g4',
 'd4f4',
 'd4e4',
 'd4c4',
 'd4b4',
 'd4a4',
 'd4e3',
 'd4d3',
 'd4c3',
 'd4f2',
 'd4d2',
 'd4b2',
 'd4g1',
 'd4d1',
 'd4a1',
 'd5g8',
 'd5d8',
 'd5a8',
 'd5f7',
 'd5d7',
 'd5b7',
 'd5e6',
 'd5d6',
 'd5c6',
 'd5h5',
 'd5g5',
 'd5f5',
 'd5e5',
 'd5c5',
 'd5b5',
 'd5a5',
 'd5e4',
 'd5d4',
 'd5c4',
 'd5f3',
 'd5d3',
 'd5b3',
 'd5g2',
 'd5d2',
 'd5a2',
 'd5h1',
 'd5d1',
 'd6f8',
 'd6d8',
 'd6b8',
 'd6e7',
 'd6d7',
 'd6c7',
 'd6h6',
 'd6g6',
 'd6f6',
 'd6e6',
 'd6c6',
 'd6b6',
 'd6a6',
 'd6e5',
 'd6d5',
 'd6c5',
 'd6f4',
 'd6d4',
 'd6b4',
 'd6g3',
 'd6d3',
 'd6a3',
 'd6h2',
 'd6d2',
 'd6d1',
 'd7e8',
 'd7d8',
 'd7c8',
 'd7h7',
 'd7g7',
 'd7f7',
 'd7e7',
 'd7c7',
 'd7b7',
 'd7a7',
 'd7e6',
 'd7d6',
 'd7c6',
 'd7f5',
 'd7d5',
 'd7b5',
 'd7g4',
 'd7d4',
 'd7a4',
 'd7h3',
 'd7d3',
 'd7d2',
 'd7d1',
 'd8h8',
 'd8g8',
 'd8f8',
 'd8e8',
 'd8c8',
 'd8b8',
 'd8a8',
 'd8e7',
 'd8d7',
 'd8c7',
 'd8f6',
 'd8d6',
 'd8b6',
 'd8g5',
 'd8d5',
 'd8a5',
 'd8h4',
 'd8d4',
 'd8d3',
 'd8d2',
 'd8d1',
 'e1e8',
 'e1e7',
 'e1e6',
 'e1e5',
 'e1a5',
 'e1h4',
 'e1e4',
 'e1b4',
 'e1g3',
 'e1e3',
 'e1c3',
 'e1f2',
 'e1e2',
 'e1d2',
 'e1h1',
 'e1g1',
 'e1f1',
 'e1d1',
 'e1c1',
 'e1b1',
 'e1a1',
 'e2e8',
 'e2e7',
 'e2e6',
 'e2a6',
 'e2h5',
 'e2e5',
 'e2b5',
 'e2g4',
 'e2e4',
 'e2c4',
 'e2f3',
 'e2e3',
 'e2d3',
 'e2h2',
 'e2g2',
 'e2f2',
 'e2d2',
 'e2c2',
 'e2b2',
 'e2a2',
 'e2f1',
 'e2e1',
 'e2d1',
 'e3e8',
 'e3e7',
 'e3a7',
 'e3h6',
 'e3e6',
 'e3b6',
 'e3g5',
 'e3e5',
 'e3c5',
 'e3f4',
 'e3e4',
 'e3d4',
 'e3h3',
 'e3g3',
 'e3f3',
 'e3d3',
 'e3c3',
 'e3b3',
 'e3a3',
 'e3f2',
 'e3e2',
 'e3d2',
 'e3g1',
 'e3e1',
 'e3c1',
 'e4e8',
 'e4a8',
 'e4h7',
 'e4e7',
 'e4b7',
 'e4g6',
 'e4e6',
 'e4c6',
 'e4f5',
 'e4e5',
 'e4d5',
 'e4h4',
 'e4g4',
 'e4f4',
 'e4d4',
 'e4c4',
 'e4b4',
 'e4a4',
 'e4f3',
 'e4e3',
 'e4d3',
 'e4g2',
 'e4e2',
 'e4c2',
 'e4h1',
 'e4e1',
 'e4b1',
 'e5h8',
 'e5e8',
 'e5b8',
 'e5g7',
 'e5e7',
 'e5c7',
 'e5f6',
 'e5e6',
 'e5d6',
 'e5h5',
 'e5g5',
 'e5f5',
 'e5d5',
 'e5c5',
 'e5b5',
 'e5a5',
 'e5f4',
 'e5e4',
 'e5d4',
 'e5g3',
 'e5e3',
 'e5c3',
 'e5h2',
 'e5e2',
 'e5b2',
 'e5e1',
 'e5a1',
 'e6g8',
 'e6e8',
 'e6c8',
 'e6f7',
 'e6e7',
 'e6d7',
 'e6h6',
 'e6g6',
 'e6f6',
 'e6d6',
 'e6c6',
 'e6b6',
 'e6a6',
 'e6f5',
 'e6e5',
 'e6d5',
 'e6g4',
 'e6e4',
 'e6c4',
 'e6h3',
 'e6e3',
 'e6b3',
 'e6e2',
 'e6a2',
 'e6e1',
 'e7f8',
 'e7e8',
 'e7d8',
 'e7h7',
 'e7g7',
 'e7f7',
 'e7d7',
 'e7c7',
 'e7b7',
 'e7a7',
 'e7f6',
 'e7e6',
 'e7d6',
 'e7g5',
 'e7e5',
 'e7c5',
 'e7h4',
 'e7e4',
 'e7b4',
 'e7e3',
 'e7a3',
 'e7e2',
 'e7e1',
 'e8h8',
 'e8g8',
 'e8f8',
 'e8d8',
 'e8c8',
 'e8b8',
 'e8a8',
 'e8f7',
 'e8e7',
 'e8d7',
 'e8g6',
 'e8e6',
 'e8c6',
 'e8h5',
 'e8e5',
 'e8b5',
 'e8e4',
 'e8a4',
 'e8e3',
 'e8e2',
 'e8e1',
 'f1f8',
 'f1f7',
 'f1f6',
 'f1a6',
 'f1f5',
 'f1b5',
 'f1f4',
 'f1c4',
 'f1h3',
 'f1f3',
 'f1d3',
 'f1g2',
 'f1f2',
 'f1e2',
 'f1h1',
 'f1g1',
 'f1e1',
 'f1d1',
 'f1c1',
 'f1b1',
 'f1a1',
 'f2f8',
 'f2f7',
 'f2a7',
 'f2f6',
 'f2b6',
 'f2f5',
 'f2c5',
 'f2h4',
 'f2f4',
 'f2d4',
 'f2g3',
 'f2f3',
 'f2e3',
 'f2h2',
 'f2g2',
 'f2e2',
 'f2d2',
 'f2c2',
 'f2b2',
 'f2a2',
 'f2g1',
 'f2f1',
 'f2e1',
 'f3f8',
 'f3a8',
 'f3f7',
 'f3b7',
 'f3f6',
 'f3c6',
 'f3h5',
 'f3f5',
 'f3d5',
 'f3g4',
 'f3f4',
 'f3e4',
 'f3h3',
 'f3g3',
 'f3e3',
 'f3d3',
 'f3c3',
 'f3b3',
 'f3a3',
 'f3g2',
 'f3f2',
 'f3e2',
 'f3h1',
 'f3f1',
 'f3d1',
 'f4f8',
 'f4b8',
 'f4f7',
 'f4c7',
 'f4h6',
 'f4f6',
 'f4d6',
 'f4g5',
 'f4f5',
 'f4e5',
 'f4h4',
 ...]

In [8]:
tokenizer = {move: idx for idx, move in enumerate(all_uci_moves, start=3)}
tokenizer["<SOS>"] = 0
tokenizer["<EOS>"] = 1
tokenizer["<PAD>"] = 2
tokenizer

{'a1h8': 3,
 'a1a8': 4,
 'a1g7': 5,
 'a1a7': 6,
 'a1f6': 7,
 'a1a6': 8,
 'a1e5': 9,
 'a1a5': 10,
 'a1d4': 11,
 'a1a4': 12,
 'a1c3': 13,
 'a1a3': 14,
 'a1b2': 15,
 'a1a2': 16,
 'a1h1': 17,
 'a1g1': 18,
 'a1f1': 19,
 'a1e1': 20,
 'a1d1': 21,
 'a1c1': 22,
 'a1b1': 23,
 'a2g8': 24,
 'a2a8': 25,
 'a2f7': 26,
 'a2a7': 27,
 'a2e6': 28,
 'a2a6': 29,
 'a2d5': 30,
 'a2a5': 31,
 'a2c4': 32,
 'a2a4': 33,
 'a2b3': 34,
 'a2a3': 35,
 'a2h2': 36,
 'a2g2': 37,
 'a2f2': 38,
 'a2e2': 39,
 'a2d2': 40,
 'a2c2': 41,
 'a2b2': 42,
 'a2b1': 43,
 'a2a1': 44,
 'a3f8': 45,
 'a3a8': 46,
 'a3e7': 47,
 'a3a7': 48,
 'a3d6': 49,
 'a3a6': 50,
 'a3c5': 51,
 'a3a5': 52,
 'a3b4': 53,
 'a3a4': 54,
 'a3h3': 55,
 'a3g3': 56,
 'a3f3': 57,
 'a3e3': 58,
 'a3d3': 59,
 'a3c3': 60,
 'a3b3': 61,
 'a3b2': 62,
 'a3a2': 63,
 'a3c1': 64,
 'a3a1': 65,
 'a4e8': 66,
 'a4a8': 67,
 'a4d7': 68,
 'a4a7': 69,
 'a4c6': 70,
 'a4a6': 71,
 'a4b5': 72,
 'a4a5': 73,
 'a4h4': 74,
 'a4g4': 75,
 'a4f4': 76,
 'a4e4': 77,
 'a4d4': 78,
 'a4c4': 79,
 'a4b4': 80,
 'a4b3': 81,
 'a4a3': 82,
 'a4c2': 83,
 'a4a2': 84,
 'a4d1': 85,
 'a4a1': 86,
 'a5d8': 87,
 'a5a8': 88,
 'a5c7': 89,
 'a5a7': 90,
 'a5b6': 91,
 'a5a6': 92,
 'a5h5': 93,
 'a5g5': 94,
 'a5f5': 95,
 'a5e5': 96,
 'a5d5': 97,
 'a5c5': 98,
 'a5b5': 99,
 'a5b4': 100,
 'a5a4': 101,
 'a5c3': 102,
 'a5a3': 103,
 'a5d2': 104,
 'a5a2': 105,
 'a5e1': 106,
 'a5a1': 107,
 'a6c8': 108,
 'a6a8': 109,
 'a6b7': 110,
 'a6a7': 111,
 'a6h6': 112,
 'a6g6': 113,
 'a6f6': 114,
 'a6e6': 115,
 'a6d6': 116,
 'a6c6': 117,
 'a6b6': 118,
 'a6b5': 119,
 'a6a5': 120,
 'a6c4': 121,
 'a6a4': 122,
 'a6d3': 123,
 'a6a3': 124,
 'a6e2': 125,
 'a6a2': 126,
 'a6f1': 127,
 'a6a1': 128,
 'a7b8': 129,
 'a7a8': 130,
 'a7h7': 131,
 'a7g7': 132,
 'a7f7': 133,
 'a7e7': 134,
 'a7d7': 135,
 'a7c7': 136,
 'a7b7': 137,
 'a7b6': 138,
 'a7a6': 139,
 'a7c5': 140,
 'a7a5': 141,
 'a7d4': 142,
 'a7a4': 143,
 'a7e3': 144,
 'a7a3': 145,
 'a7f2': 146,
 'a7a2': 147,
 'a7g1': 148,
 'a7a1': 149,
 'a8h8': 150,
 'a8g8': 151,
 'a8f8': 152,
 'a8e8': 153,
 'a8d8': 154,
 'a8c8': 155,
 'a8b8': 156,
 'a8b7': 157,
 'a8a7': 158,
 'a8c6': 159,
 'a8a6': 160,
 'a8d5': 161,
 'a8a5': 162,
 'a8e4': 163,
 'a8a4': 164,
 'a8f3': 165,
 'a8a3': 166,
 'a8g2': 167,
 'a8a2': 168,
 'a8h1': 169,
 'a8a1': 170,
 'b1b8': 171,
 'b1h7': 172,
 'b1b7': 173,
 'b1g6': 174,
 'b1b6': 175,
 'b1f5': 176,
 'b1b5': 177,
 'b1e4': 178,
 'b1b4': 179,
 'b1d3': 180,
 'b1b3': 181,
 'b1c2': 182,
 'b1b2': 183,
 'b1a2': 184,
 'b1h1': 185,
 'b1g1': 186,
 'b1f1': 187,
 'b1e1': 188,
 'b1d1': 189,
 'b1c1': 190,
 'b1a1': 191,
 'b2h8': 192,
 'b2b8': 193,
 'b2g7': 194,
 'b2b7': 195,
 'b2f6': 196,
 'b2b6': 197,
 'b2e5': 198,
 'b2b5': 199,
 'b2d4': 200,
 'b2b4': 201,
 'b2c3': 202,
 'b2b3': 203,
 'b2a3': 204,
 'b2h2': 205,
 'b2g2': 206,
 'b2f2': 207,
 'b2e2': 208,
 'b2d2': 209,
 'b2c2': 210,
 'b2a2': 211,
 'b2c1': 212,
 'b2b1': 213,
 'b2a1': 214,
 'b3g8': 215,
 'b3b8': 216,
 'b3f7': 217,
 'b3b7': 218,
 'b3e6': 219,
 'b3b6': 220,
 'b3d5': 221,
 'b3b5': 222,
 'b3c4': 223,
 'b3b4': 224,
 'b3a4': 225,
 'b3h3': 226,
 'b3g3': 227,
 'b3f3': 228,
 'b3e3': 229,
 'b3d3': 230,
 'b3c3': 231,
 'b3a3': 232,
 'b3c2': 233,
 'b3b2': 234,
 'b3a2': 235,
 'b3d1': 236,
 'b3b1': 237,
 'b4f8': 238,
 'b4b8': 239,
 'b4e7': 240,
 'b4b7': 241,
 'b4d6': 242,
 'b4b6': 243,
 'b4c5': 244,
 'b4b5': 245,
 'b4a5': 246,
 'b4h4': 247,
 'b4g4': 248,
 'b4f4': 249,
 'b4e4': 250,
 'b4d4': 251,
 'b4c4': 252,
 'b4a4': 253,
 'b4c3': 254,
 'b4b3': 255,
 'b4a3': 256,
 'b4d2': 257,
 'b4b2': 258,
 'b4e1': 259,
 'b4b1': 260,
 'b5e8': 261,
 'b5b8': 262,
 'b5d7': 263,
 'b5b7': 264,
 'b5c6': 265,
 'b5b6': 266,
 'b5a6': 267,
 'b5h5': 268,
 'b5g5': 269,
 'b5f5': 270,
 'b5e5': 271,
 'b5d5': 272,
 'b5c5': 273,
 'b5a5': 274,
 'b5c4': 275,
 'b5b4': 276,
 'b5a4': 277,
 'b5d3': 278,
 'b5b3': 279,
 'b5e2': 280,
 'b5b2': 281,
 'b5f1': 282,
 'b5b1': 283,
 'b6d8': 284,
 'b6b8': 285,
 'b6c7': 286,
 'b6b7': 287,
 'b6a7': 288,
 'b6h6': 289,
 'b6g6': 290,
 'b6f6': 291,
 'b6e6': 292,
 'b6d6': 293,
 'b6c6': 294,
 'b6a6': 295,
 'b6c5': 296,
 'b6b5': 297,
 'b6a5': 298,
 'b6d4': 299,
 'b6b4': 300,
 'b6e3': 301,
 'b6b3': 302,
 'b6f2': 303,
 'b6b2': 304,
 'b6g1': 305,
 'b6b1': 306,
 'b7c8': 307,
 'b7b8': 308,
 'b7a8': 309,
 'b7h7': 310,
 'b7g7': 311,
 'b7f7': 312,
 'b7e7': 313,
 'b7d7': 314,
 'b7c7': 315,
 'b7a7': 316,
 'b7c6': 317,
 'b7b6': 318,
 'b7a6': 319,
 'b7d5': 320,
 'b7b5': 321,
 'b7e4': 322,
 'b7b4': 323,
 'b7f3': 324,
 'b7b3': 325,
 'b7g2': 326,
 'b7b2': 327,
 'b7h1': 328,
 'b7b1': 329,
 'b8h8': 330,
 'b8g8': 331,
 'b8f8': 332,
 'b8e8': 333,
 'b8d8': 334,
 'b8c8': 335,
 'b8a8': 336,
 'b8c7': 337,
 'b8b7': 338,
 'b8a7': 339,
 'b8d6': 340,
 'b8b6': 341,
 'b8e5': 342,
 'b8b5': 343,
 'b8f4': 344,
 'b8b4': 345,
 'b8g3': 346,
 'b8b3': 347,
 'b8h2': 348,
 'b8b2': 349,
 'b8b1': 350,
 'c1c8': 351,
 'c1c7': 352,
 'c1h6': 353,
 'c1c6': 354,
 'c1g5': 355,
 'c1c5': 356,
 'c1f4': 357,
 'c1c4': 358,
 'c1e3': 359,
 'c1c3': 360,
 'c1a3': 361,
 'c1d2': 362,
 'c1c2': 363,
 'c1b2': 364,
 'c1h1': 365,
 'c1g1': 366,
 'c1f1': 367,
 'c1e1': 368,
 'c1d1': 369,
 'c1b1': 370,
 'c1a1': 371,
 'c2c8': 372,
 'c2h7': 373,
 'c2c7': 374,
 'c2g6': 375,
 'c2c6': 376,
 'c2f5': 377,
 'c2c5': 378,
 'c2e4': 379,
 'c2c4': 380,
 'c2a4': 381,
 'c2d3': 382,
 'c2c3': 383,
 'c2b3': 384,
 'c2h2': 385,
 'c2g2': 386,
 'c2f2': 387,
 'c2e2': 388,
 'c2d2': 389,
 'c2b2': 390,
 'c2a2': 391,
 'c2d1': 392,
 'c2c1': 393,
 'c2b1': 394,
 'c3h8': 395,
 'c3c8': 396,
 'c3g7': 397,
 'c3c7': 398,
 'c3f6': 399,
 'c3c6': 400,
 'c3e5': 401,
 'c3c5': 402,
 'c3a5': 403,
 'c3d4': 404,
 'c3c4': 405,
 'c3b4': 406,
 'c3h3': 407,
 'c3g3': 408,
 'c3f3': 409,
 'c3e3': 410,
 'c3d3': 411,
 'c3b3': 412,
 'c3a3': 413,
 'c3d2': 414,
 'c3c2': 415,
 'c3b2': 416,
 'c3e1': 417,
 'c3c1': 418,
 'c3a1': 419,
 'c4g8': 420,
 'c4c8': 421,
 'c4f7': 422,
 'c4c7': 423,
 'c4e6': 424,
 'c4c6': 425,
 'c4a6': 426,
 'c4d5': 427,
 'c4c5': 428,
 'c4b5': 429,
 'c4h4': 430,
 'c4g4': 431,
 'c4f4': 432,
 'c4e4': 433,
 'c4d4': 434,
 'c4b4': 435,
 'c4a4': 436,
 'c4d3': 437,
 'c4c3': 438,
 'c4b3': 439,
 'c4e2': 440,
 'c4c2': 441,
 'c4a2': 442,
 'c4f1': 443,
 'c4c1': 444,
 'c5f8': 445,
 'c5c8': 446,
 'c5e7': 447,
 'c5c7': 448,
 'c5a7': 449,
 'c5d6': 450,
 'c5c6': 451,
 'c5b6': 452,
 'c5h5': 453,
 'c5g5': 454,
 'c5f5': 455,
 'c5e5': 456,
 'c5d5': 457,
 'c5b5': 458,
 'c5a5': 459,
 'c5d4': 460,
 'c5c4': 461,
 'c5b4': 462,
 'c5e3': 463,
 'c5c3': 464,
 'c5a3': 465,
 'c5f2': 466,
 'c5c2': 467,
 'c5g1': 468,
 'c5c1': 469,
 'c6e8': 470,
 'c6c8': 471,
 'c6a8': 472,
 'c6d7': 473,
 'c6c7': 474,
 'c6b7': 475,
 'c6h6': 476,
 'c6g6': 477,
 'c6f6': 478,
 'c6e6': 479,
 'c6d6': 480,
 'c6b6': 481,
 'c6a6': 482,
 'c6d5': 483,
 'c6c5': 484,
 'c6b5': 485,
 'c6e4': 486,
 'c6c4': 487,
 'c6a4': 488,
 'c6f3': 489,
 'c6c3': 490,
 'c6g2': 491,
 'c6c2': 492,
 'c6h1': 493,
 'c6c1': 494,
 'c7d8': 495,
 'c7c8': 496,
 'c7b8': 497,
 'c7h7': 498,
 'c7g7': 499,
 'c7f7': 500,
 'c7e7': 501,
 'c7d7': 502,
 'c7b7': 503,
 'c7a7': 504,
 'c7d6': 505,
 'c7c6': 506,
 'c7b6': 507,
 'c7e5': 508,
 'c7c5': 509,
 'c7a5': 510,
 'c7f4': 511,
 'c7c4': 512,
 'c7g3': 513,
 'c7c3': 514,
 'c7h2': 515,
 'c7c2': 516,
 'c7c1': 517,
 'c8h8': 518,
 'c8g8': 519,
 'c8f8': 520,
 'c8e8': 521,
 'c8d8': 522,
 'c8b8': 523,
 'c8a8': 524,
 'c8d7': 525,
 'c8c7': 526,
 'c8b7': 527,
 'c8e6': 528,
 'c8c6': 529,
 'c8a6': 530,
 'c8f5': 531,
 'c8c5': 532,
 'c8g4': 533,
 'c8c4': 534,
 'c8h3': 535,
 'c8c3': 536,
 'c8c2': 537,
 'c8c1': 538,
 'd1d8': 539,
 'd1d7': 540,
 'd1d6': 541,
 'd1h5': 542,
 'd1d5': 543,
 'd1g4': 544,
 'd1d4': 545,
 'd1a4': 546,
 'd1f3': 547,
 'd1d3': 548,
 'd1b3': 549,
 'd1e2': 550,
 'd1d2': 551,
 'd1c2': 552,
 'd1h1': 553,
 'd1g1': 554,
 'd1f1': 555,
 'd1e1': 556,
 'd1c1': 557,
 'd1b1': 558,
 'd1a1': 559,
 'd2d8': 560,
 'd2d7': 561,
 'd2h6': 562,
 'd2d6': 563,
 'd2g5': 564,
 'd2d5': 565,
 'd2a5': 566,
 'd2f4': 567,
 'd2d4': 568,
 'd2b4': 569,
 'd2e3': 570,
 'd2d3': 571,
 'd2c3': 572,
 'd2h2': 573,
 'd2g2': 574,
 'd2f2': 575,
 'd2e2': 576,
 'd2c2': 577,
 'd2b2': 578,
 'd2a2': 579,
 'd2e1': 580,
 'd2d1': 581,
 'd2c1': 582,
 'd3d8': 583,
 'd3h7': 584,
 'd3d7': 585,
 'd3g6': 586,
 'd3d6': 587,
 'd3a6': 588,
 'd3f5': 589,
 'd3d5': 590,
 'd3b5': 591,
 'd3e4': 592,
 'd3d4': 593,
 'd3c4': 594,
 'd3h3': 595,
 'd3g3': 596,
 'd3f3': 597,
 'd3e3': 598,
 'd3c3': 599,
 'd3b3': 600,
 'd3a3': 601,
 'd3e2': 602,
 'd3d2': 603,
 'd3c2': 604,
 'd3f1': 605,
 'd3d1': 606,
 'd3b1': 607,
 'd4h8': 608,
 'd4d8': 609,
 'd4g7': 610,
 'd4d7': 611,
 'd4a7': 612,
 'd4f6': 613,
 'd4d6': 614,
 'd4b6': 615,
 'd4e5': 616,
 'd4d5': 617,
 'd4c5': 618,
 'd4h4': 619,
 'd4g4': 620,
 'd4f4': 621,
 'd4e4': 622,
 'd4c4': 623,
 'd4b4': 624,
 'd4a4': 625,
 'd4e3': 626,
 'd4d3': 627,
 'd4c3': 628,
 'd4f2': 629,
 'd4d2': 630,
 'd4b2': 631,
 'd4g1': 632,
 'd4d1': 633,
 'd4a1': 634,
 'd5g8': 635,
 'd5d8': 636,
 'd5a8': 637,
 'd5f7': 638,
 'd5d7': 639,
 'd5b7': 640,
 'd5e6': 641,
 'd5d6': 642,
 'd5c6': 643,
 'd5h5': 644,
 'd5g5': 645,
 'd5f5': 646,
 'd5e5': 647,
 'd5c5': 648,
 'd5b5': 649,
 'd5a5': 650,
 'd5e4': 651,
 'd5d4': 652,
 'd5c4': 653,
 'd5f3': 654,
 'd5d3': 655,
 'd5b3': 656,
 'd5g2': 657,
 'd5d2': 658,
 'd5a2': 659,
 'd5h1': 660,
 'd5d1': 661,
 'd6f8': 662,
 'd6d8': 663,
 'd6b8': 664,
 'd6e7': 665,
 'd6d7': 666,
 'd6c7': 667,
 'd6h6': 668,
 'd6g6': 669,
 'd6f6': 670,
 'd6e6': 671,
 'd6c6': 672,
 'd6b6': 673,
 'd6a6': 674,
 'd6e5': 675,
 'd6d5': 676,
 'd6c5': 677,
 'd6f4': 678,
 'd6d4': 679,
 'd6b4': 680,
 'd6g3': 681,
 'd6d3': 682,
 'd6a3': 683,
 'd6h2': 684,
 'd6d2': 685,
 'd6d1': 686,
 'd7e8': 687,
 'd7d8': 688,
 'd7c8': 689,
 'd7h7': 690,
 'd7g7': 691,
 'd7f7': 692,
 'd7e7': 693,
 'd7c7': 694,
 'd7b7': 695,
 'd7a7': 696,
 'd7e6': 697,
 'd7d6': 698,
 'd7c6': 699,
 'd7f5': 700,
 'd7d5': 701,
 'd7b5': 702,
 'd7g4': 703,
 'd7d4': 704,
 'd7a4': 705,
 'd7h3': 706,
 'd7d3': 707,
 'd7d2': 708,
 'd7d1': 709,
 'd8h8': 710,
 'd8g8': 711,
 'd8f8': 712,
 'd8e8': 713,
 'd8c8': 714,
 'd8b8': 715,
 'd8a8': 716,
 'd8e7': 717,
 'd8d7': 718,
 'd8c7': 719,
 'd8f6': 720,
 'd8d6': 721,
 'd8b6': 722,
 'd8g5': 723,
 'd8d5': 724,
 'd8a5': 725,
 'd8h4': 726,
 'd8d4': 727,
 'd8d3': 728,
 'd8d2': 729,
 'd8d1': 730,
 'e1e8': 731,
 'e1e7': 732,
 'e1e6': 733,
 'e1e5': 734,
 'e1a5': 735,
 'e1h4': 736,
 'e1e4': 737,
 'e1b4': 738,
 'e1g3': 739,
 'e1e3': 740,
 'e1c3': 741,
 'e1f2': 742,
 'e1e2': 743,
 'e1d2': 744,
 'e1h1': 745,
 'e1g1': 746,
 'e1f1': 747,
 'e1d1': 748,
 'e1c1': 749,
 'e1b1': 750,
 'e1a1': 751,
 'e2e8': 752,
 'e2e7': 753,
 'e2e6': 754,
 'e2a6': 755,
 'e2h5': 756,
 'e2e5': 757,
 'e2b5': 758,
 'e2g4': 759,
 'e2e4': 760,
 'e2c4': 761,
 'e2f3': 762,
 'e2e3': 763,
 'e2d3': 764,
 'e2h2': 765,
 'e2g2': 766,
 'e2f2': 767,
 'e2d2': 768,
 'e2c2': 769,
 'e2b2': 770,
 'e2a2': 771,
 'e2f1': 772,
 'e2e1': 773,
 'e2d1': 774,
 'e3e8': 775,
 'e3e7': 776,
 'e3a7': 777,
 'e3h6': 778,
 'e3e6': 779,
 'e3b6': 780,
 'e3g5': 781,
 'e3e5': 782,
 'e3c5': 783,
 'e3f4': 784,
 'e3e4': 785,
 'e3d4': 786,
 'e3h3': 787,
 'e3g3': 788,
 'e3f3': 789,
 'e3d3': 790,
 'e3c3': 791,
 'e3b3': 792,
 'e3a3': 793,
 'e3f2': 794,
 'e3e2': 795,
 'e3d2': 796,
 'e3g1': 797,
 'e3e1': 798,
 'e3c1': 799,
 'e4e8': 800,
 'e4a8': 801,
 'e4h7': 802,
 'e4e7': 803,
 'e4b7': 804,
 'e4g6': 805,
 'e4e6': 806,
 'e4c6': 807,
 'e4f5': 808,
 'e4e5': 809,
 'e4d5': 810,
 'e4h4': 811,
 'e4g4': 812,
 'e4f4': 813,
 'e4d4': 814,
 'e4c4': 815,
 'e4b4': 816,
 'e4a4': 817,
 'e4f3': 818,
 'e4e3': 819,
 'e4d3': 820,
 'e4g2': 821,
 'e4e2': 822,
 'e4c2': 823,
 'e4h1': 824,
 'e4e1': 825,
 'e4b1': 826,
 'e5h8': 827,
 'e5e8': 828,
 'e5b8': 829,
 'e5g7': 830,
 'e5e7': 831,
 'e5c7': 832,
 'e5f6': 833,
 'e5e6': 834,
 'e5d6': 835,
 'e5h5': 836,
 'e5g5': 837,
 'e5f5': 838,
 'e5d5': 839,
 'e5c5': 840,
 'e5b5': 841,
 'e5a5': 842,
 'e5f4': 843,
 'e5e4': 844,
 'e5d4': 845,
 'e5g3': 846,
 'e5e3': 847,
 'e5c3': 848,
 'e5h2': 849,
 'e5e2': 850,
 'e5b2': 851,
 'e5e1': 852,
 'e5a1': 853,
 'e6g8': 854,
 'e6e8': 855,
 'e6c8': 856,
 'e6f7': 857,
 'e6e7': 858,
 'e6d7': 859,
 'e6h6': 860,
 'e6g6': 861,
 'e6f6': 862,
 'e6d6': 863,
 'e6c6': 864,
 'e6b6': 865,
 'e6a6': 866,
 'e6f5': 867,
 'e6e5': 868,
 'e6d5': 869,
 'e6g4': 870,
 'e6e4': 871,
 'e6c4': 872,
 'e6h3': 873,
 'e6e3': 874,
 'e6b3': 875,
 'e6e2': 876,
 'e6a2': 877,
 'e6e1': 878,
 'e7f8': 879,
 'e7e8': 880,
 'e7d8': 881,
 'e7h7': 882,
 'e7g7': 883,
 'e7f7': 884,
 'e7d7': 885,
 'e7c7': 886,
 'e7b7': 887,
 'e7a7': 888,
 'e7f6': 889,
 'e7e6': 890,
 'e7d6': 891,
 'e7g5': 892,
 'e7e5': 893,
 'e7c5': 894,
 'e7h4': 895,
 'e7e4': 896,
 'e7b4': 897,
 'e7e3': 898,
 'e7a3': 899,
 'e7e2': 900,
 'e7e1': 901,
 'e8h8': 902,
 'e8g8': 903,
 'e8f8': 904,
 'e8d8': 905,
 'e8c8': 906,
 'e8b8': 907,
 'e8a8': 908,
 'e8f7': 909,
 'e8e7': 910,
 'e8d7': 911,
 'e8g6': 912,
 'e8e6': 913,
 'e8c6': 914,
 'e8h5': 915,
 'e8e5': 916,
 'e8b5': 917,
 'e8e4': 918,
 'e8a4': 919,
 'e8e3': 920,
 'e8e2': 921,
 'e8e1': 922,
 'f1f8': 923,
 'f1f7': 924,
 'f1f6': 925,
 'f1a6': 926,
 'f1f5': 927,
 'f1b5': 928,
 'f1f4': 929,
 'f1c4': 930,
 'f1h3': 931,
 'f1f3': 932,
 'f1d3': 933,
 'f1g2': 934,
 'f1f2': 935,
 'f1e2': 936,
 'f1h1': 937,
 'f1g1': 938,
 'f1e1': 939,
 'f1d1': 940,
 'f1c1': 941,
 'f1b1': 942,
 'f1a1': 943,
 'f2f8': 944,
 'f2f7': 945,
 'f2a7': 946,
 'f2f6': 947,
 'f2b6': 948,
 'f2f5': 949,
 'f2c5': 950,
 'f2h4': 951,
 'f2f4': 952,
 'f2d4': 953,
 'f2g3': 954,
 'f2f3': 955,
 'f2e3': 956,
 'f2h2': 957,
 'f2g2': 958,
 'f2e2': 959,
 'f2d2': 960,
 'f2c2': 961,
 'f2b2': 962,
 'f2a2': 963,
 'f2g1': 964,
 'f2f1': 965,
 'f2e1': 966,
 'f3f8': 967,
 'f3a8': 968,
 'f3f7': 969,
 'f3b7': 970,
 'f3f6': 971,
 'f3c6': 972,
 'f3h5': 973,
 'f3f5': 974,
 'f3d5': 975,
 'f3g4': 976,
 'f3f4': 977,
 'f3e4': 978,
 'f3h3': 979,
 'f3g3': 980,
 'f3e3': 981,
 'f3d3': 982,
 'f3c3': 983,
 'f3b3': 984,
 'f3a3': 985,
 'f3g2': 986,
 'f3f2': 987,
 'f3e2': 988,
 'f3h1': 989,
 'f3f1': 990,
 'f3d1': 991,
 'f4f8': 992,
 'f4b8': 993,
 'f4f7': 994,
 'f4c7': 995,
 'f4h6': 996,
 'f4f6': 997,
 'f4d6': 998,
 'f4g5': 999,
 'f4f5': 1000,
 'f4e5': 1001,
 'f4h4': 1002,
 ...}

In [9]:
df2 = pl.read_parquet("../data/tokenized_games.parquet")
df2

shape: (50_000, 1)
┌────────────────┐
│ token_ids      │
│ ---            │
│ list[u16]      │
╞════════════════╡
│ [0, 760, … 1]  │
│ [0, 760, … 1]  │
│ [0, 760, … 1]  │
│ [0, 760, … 1]  │
│ [0, 1140, … 1] │
│ …              │
│ [0, 760, … 1]  │
│ [0, 760, … 1]  │
│ [0, 1732, … 1] │
│ [0, 760, … 1]  │
│ [0, 1143, … 1] │
└────────────────┘

In [10]:
# length of longest game
max_length = df2["token_ids"].list.len().max()
max_length

390

In [17]:
max_length_og_id = df["moves"].str.split(" ").list.len().arg_max()
max_length_og = df[max_length_og_id]["moves"].item()
print(max_length_og)
print(len(max_length_og.split(" ")))

d2d4 g8f6 g1f3 g7g6 c2c4 f8g7 b1c3 e8g8 e2e4 d7d6 f1e2 e7e5 e1g1 e5d4 f3d4 f8e8 f2f3 b8c6 c1e3 c6d4 e3d4 g7h6 d1c2 c7c6 a1d1 d8e7 e2d3 a7a6 a2a4 c8e6 f3f4 f6g4 d3e2 a8c8 c2d3 e7h4 h2h3 c6c5 d4c5 c8c5 e2g4 e6c4 d3d6 h6f8 d6d7 c5c8 g4e2 c4e6 d7d3 e6b3 d1a1 e8d8 c3d5 b3d5 e4d5 c8c5 a1d1 c5d5 d3d5 d8d5 d1d5 f8h6 d5d7 h6f4 d7b7 h4g3 b2b3 g3h2 g1f2 h2g3 f2g1 g3h2 g1f2 g8f8 b7d7 h2g3 f2g1 g3h2 g1f2 f8e8 d7b7 h2g3 f2g1 g3h2 g1f2 f4g3 f2e3 g3c7 e2f3 h2e5 e3d3 e5f5 d3c3 c7e5 c3d2 e5f4 d2c3 f4e5 c3d2 e8f8 f1d1 e5d4 d1e1 d4f6 e1d1 f5e5 d2d3 h7h5 d1d2 f8g7 d3c2 e5c3 c2d1 f6d4 d2c2 c3d3 c2d2 d3f1 d1c2 f1a1 d2d3 a1b2 c2d1 d4c3 f3d5 g7h6 b7f7 c3b4 d5c4 h5h4 f7f4 b2b1 d1e2 b1e1 e2f3 e1g3 f3e4 g3g2 f4f3 g2g5 d3d5 g5e7 d5e5 e7b7 e5d5 b7e7 d5e5 e7b7 e4e3 a6a5 e5e4 b4d2 e3d4 b7g7 d4d3 d2g5 d3e2 g7b2 e2f1 g5f6 e4g4 b2e5 f1g2 g6g5 c4d3 e5b2 g2f1 b2a1 f1e2 f6c3 e2f2 c3d4 f2e2 d4c3 e2f2 a1h1 g4c4 h1h2 f2f1 h2h1 f1f2 c3e1 f2e3 h1g1 e3e4 g1b6 e4d5 b6d8 d5e4 d8b6 e4d5 b6d8 d5e4 d8e7 e4d4 e7a7 d4e4 a7e7 e4d4 e7d6 d4e3 h6h5 e3e2 e1b4 e2f1 d6h2 c4c2 h2h1 f1f2 b4e1 f2e3 h1g1 e3e4 g1a7 f3f5 a7e7 e4f3 e7d6 f3e4 d6e7 f5e5 e7b4 d3c4 e1g3 e5c5 h5h6 c5c6 h6g7 c2e2 g5g4 h3g4 h4h3 e4f3 g3d6 f3f2 b4b7 c6d6 b7g2 f2e3 g2g3 e3e4 g3d6 e4f3 g7h8 e2e8 h8g7 e8e2 d6b8 e2d2 b8e5 d2e2 e5c7 e2d2 c7e5 d2e2 e5c7 e2d2 c7e7 d2h2 e7h4 f3f4 g7f8 f4f3 f8e7 c4b5 e7e6 b5c4 e6d6 h2d2 d6c7 d2h2 c7d6 h2d2 d6c6 d2h2 c6c5 c4b5 c5d6 b5c4 d6c7 c4b5 c7d6 b5c4 d6c5 c4b5 c5d5 b5c4 d5d4 c4b5 d4c5 b5c4 c5b4 g4g5 b4a3 g5g6 h4f6 f3g4 f6g6 g4h3 g6h6 h3g3 h6d6 g3h3 d6f4 h2g2 f4d4 g2g3 d4e4 g3g5 e4f3 h3h4 f3f4 h4h5 f4f3 h5h4 f3f2 h4g4 f2g1 g4f4 g1c1 f4f5 c1e3 f5g6 e3b6 g6h5 b6b4 g5d5 b4e7 d5a5 e7e8 h5g4 e8e4 g4h3 e4h1 h3g4 h1d1 g4h3 d1d7 h3h4 d7d8 a5g5 d8e7 a4a5 a3b4 a5a6 e7e4 h4g3 e4e3 g3g4 e3g1 g4f4 g1f2 f4e4 f2h4 e4f5 h4h7 f5f4 h7h4 g5g4 h4h2 f4g5 b4c5 g4e4 h2g2 g5f4 g2f2 f4g4 f2g1 g4f5 g1f2 f5e6 f2f8 e4e5 c5c6 e5e2 f8h6 e6f5 h6h7 f5g5 c6b6 e2e5 h7g7 g5f5 g7h7 f5g4 h7g7 g4f4 b6a7
388