In [1]:
import polars as pl

In [2]:
df = pl.read_parquet("../data/parquet/*.parquet")
df

shape: (50_000, 5)
┌───────────┬───────────┬────────┬────────────────────────────────┬────────────────────────────────┐
│ white_elo ┆ black_elo ┆ result ┆ moves                          ┆ opening                        │
│ ---       ┆ ---       ┆ ---    ┆ ---                            ┆ ---                            │
│ i32       ┆ i32       ┆ i8     ┆ str                            ┆ str                            │
╞═══════════╪═══════════╪════════╪════════════════════════════════╪════════════════════════════════╡
│ 2071      ┆ 2030      ┆ 1      ┆ e2e4 e7e5 g1f3 d7d6 d2d4 e5d4  ┆ Philidor Defense: Exchange     │
│           ┆           ┆        ┆ …                              ┆ Var…                           │
│ 2098      ┆ 2152      ┆ 1      ┆ e2e4 e7e5 g1f3 g8f6 b1c3 b8c6  ┆ Four Knights Game: Scotch      │
│           ┆           ┆        ┆ …                              ┆ Vari…                          │
│ 2080      ┆ 2180      ┆ -1     ┆ e2e4 e7e5 g1f3 g8f6 b1c3 f8b4  ┆ Russian Game: Three Knights    │
│           ┆           ┆        ┆ …                              ┆ Ga…                            │
│ 2072      ┆ 2067      ┆ 1      ┆ e2e4 c7c5 g1f3 d7d6 d2d4 c5d4  ┆ Sicilian Defense: Najdorf      │
│           ┆           ┆        ┆ …                              ┆ Vari…                          │
│ 2091      ┆ 2001      ┆ -1     ┆ g2g4 d7d5 f1g2 c7c6 h2h3 e7e5  ┆ Grob Opening: Keene Defense    │
│           ┆           ┆        ┆ …                              ┆                                │
│ …         ┆ …         ┆ …      ┆ …                              ┆ …                              │
│ 2131      ┆ 2133      ┆ -1     ┆ e2e4 c7c5 g1f3 e7e6 d2d4 c5d4  ┆ Sicilian Defense: Kan          │
│           ┆           ┆        ┆ …                              ┆ Variatio…                      │
│ 2171      ┆ 2112      ┆ 1      ┆ e2e4 g7g6 d2d4 f8g7 b1c3 a7a6  ┆ Modern Defense: Standard Line  │
│           ┆           ┆        ┆ …                              ┆                                │
│ 2072      ┆ 2290      ┆ 1      ┆ g1f3 g7g6 d2d4 f8g7 c2c4 b7b6  ┆ Zukertort Opening: Kingside    │
│           ┆           ┆        ┆ …                              ┆ Fi…                            │
│ 2175      ┆ 2227      ┆ -1     ┆ e2e4 d7d6 d2d4 g8f6 b1c3 b8d7  ┆ Lion Defense: Anti-Philidor,   │
│           ┆           ┆        ┆ …                              ┆ L…                             │
│ 2232      ┆ 2115      ┆ -1     ┆ g2g3 c7c5 f1g2 g8f6 d2d3 b8c6  ┆ Hungarian Opening: Sicilian    │
│           ┆           ┆        ┆ …                              ┆ In…                            │
└───────────┴───────────┴────────┴────────────────────────────────┴────────────────────────────────┘

In [3]:
# opening is whatever is before :, before , and without any #2, #3, etc. suffixes
# normalize whitespace so e.g. 'Vienna Game' and 'Vienna Game ' dedupe correctly
openings = (
    df["opening"]
    .str.split(":")
    .list.get(0)
    .str.split(",")
    .list.get(0)
    .str.replace(r"#\d+", "")
    .str.strip_chars()
    .str.replace_all(r"\s+", " ")
    .unique()
    .sort()
)

for opening in openings:
    print(opening)

Alekhine Defense
Amar Opening
Amazon Attack
Anderssen Opening
Anderssen's Opening
Australian Defense
Barnes Defense
Barnes Opening
Benko Gambit
Benko Gambit Accepted
Benko Gambit Declined
Benoni Defense
Bird Opening
Bishop's Opening
Blackmar-Diemer Gambit
Blackmar-Diemer Gambit Accepted
Blackmar-Diemer Gambit Declined
Blumenfeld Countergambit
Blumenfeld Countergambit Accepted
Bogo-Indian Defense
Borg Defense
Budapest Defense
Canard Opening
Caro-Kann Defense
Carr Defense
Catalan Opening
Center Game
Center Game Accepted
Clemenz Opening
Colle System
Czech Defense
Danish Gambit
Danish Gambit Accepted
Danish Gambit Declined
Duras Gambit
Dutch Defense
East Indian Defense
Elephant Gambit
English Defense
English Opening
English Orangutan
Englund Gambit
Englund Gambit Complex
Englund Gambit Complex Declined
Englund Gambit Declined
Four Knights
Four Knights Game
Franco-Benoni Defense
French Defense
Gedult's Opening
Giuoco Piano
Goldsmith Defense
Grob Opening
Gruenfeld Defense
Grünfeld Defense
Guatemala Defense
Gunderam Defense
Hippopotamus Defense
Horwitz Defense
Hungarian Opening
Indian Defense
Indian Game
Italian Game
Kadas Opening
Kangaroo Defense
King's Gambit
King's Gambit Accepted
King's Gambit Declined
King's Indian
King's Indian Attack
King's Indian Defense
King's Knight Opening
King's Pawn
King's Pawn Game
King's Pawn Opening
Kádas Opening
Lasker Simul Special
Latvian Gambit
Latvian Gambit Accepted
Lion Defense
London System
Marienbad System
Mexican Defense
Mieses Opening
Mikenas Defense
Modern Defense
Montevideo Defense
Neo-Gruenfeld Defense
Neo-Grünfeld Defense
Nimzo-Indian Defense
Nimzo-Larsen Attack
Nimzowitsch Defense
Nimzowitsch-Larsen Attack
Old Benoni Defense
Old Indian
Old Indian Defense
Owen Defense
Paleface Attack
Petrov
Petrov's Defense
Philidor Defense
Pirc Defense
Polish Defense
Polish Opening
Ponziani Opening
Portuguese Opening
Pseudo Queen's Indian Defense
Pterodactyl Defense
Queen's Gambit
Queen's Gambit Accepted
Queen's Gambit Declined
Queen's Gambit Refused
Queen's Indian Accelerated
Queen's Indian Defense
Queen's Pawn
Queen's Pawn Game
Queen's Pawn Opening
Rapport-Jobava System
Rat Defense
Reti Opening
Richter-Veresov Attack
Robatsch (Modern) Defense
Robatsch Defense
Rubinstein Opening
Russian Game
Ruy Lopez
Réti Opening
Saragossa Opening
Scandinavian Defense
Scotch Gambit
Scotch Game
Semi-Benoni
Semi-Bononi
Semi-Slav Defense
Semi-Slav Defense Accepted
Sicilian Defense
Slav Defense
Slav Indian
Sodium Attack
St. George Defense
System
Tarrasch Defense
Three Knights Opening
Torre Attack
Trompowsky Attack
Valencia Opening
Van Geet Opening
Van't Kruijs Opening
Vienna Gambit
Vienna Game
Vulture Defense
Wade Defense
Ware Defense
Ware Opening
Yusupov-Rubinstein System
Zukertort Opening

In [4]:
moves = df[0]["moves"].to_list()[0]
print(moves)

e2e4 e7e5 g1f3 d7d6 d2d4 e5d4 f3d4 f8e7 f1c4 g8f6 b1c3 e8g8 e1g1 a7a6 a2a3 c7c5 d4e2 b8c6 f2f4 c8g4 d1e1 b7b5 c4d5 f6d5 c3d5 c6d4 e2d4 c5d4 f4f5 f7f6 c1f4 a8c8 e1d2 g4h5 a1c1 h5f7 d2d4 c8c4 d4d3 f7d5 d3d5 g8h8 c2c3 d8b6 g1h1 a6a5 c1d1 c4c6 d5e6 b5b4 e6e7 f8d8 c3b4 a5b4 a3b4 h7h6 b4b5 c6c8 d1d6 d8d6 f4d6 b6b5 f1e1 c8e8 e7c7 e8e4 e1c1 b5f5 h2h3 e4e2 b2b4 f5f2 c7c8 h8h7 c8g4 e2b2 d6c5 f2d2 c1d1 d2c2 d1e1 f6f5 g4g3

In [9]:
moves = df["moves"].str.split(" ")
moves

shape: (50_000,)
Series: 'moves' [list[str]]
[
	["e2e4", "e7e5", … "g4g3"]
	["e2e4", "e7e5", … "e5d6"]
	["e2e4", "e7e5", … "c2g2"]
	["e2e4", "c7c5", … "e1e4"]
	["g2g4", "d7d5", … "f2f1"]
	…
	["e2e4", "c7c5", … "g5b5"]
	["e2e4", "g7g6", … "d3g6"]
	["g1f3", "g7g6", … "f7d7"]
	["e2e4", "d7d6", … "e5f4"]
	["g2g3", "c7c5", … "b7b3"]
]

In [14]:
all_moves = moves.explode().unique().sort()  # just experimenting, they are not all possible moves
all_moves

shape: (1_910,)
Series: 'moves' [str]
[
	"a1a2"
	"a1a3"
	"a1a4"
	"a1a5"
	"a1a6"
	…
	"h8h3"
	"h8h4"
	"h8h5"
	"h8h6"
	"h8h7"
]

In [ ]:
with open("../data/all_uci_moves.txt", "r") as f:
    all_uci_moves = [line.strip() for line in f]


tokenizer = {move: idx for idx, move in enumerate(all_uci_moves, start=2)}
tokenizer["<SOS>"] = 0
tokenizer["<EOS>"] = 1

{'a1h8': 2,
 'a1a8': 3,
 'a1g7': 4,
 'a1a7': 5,
 'a1f6': 6,
 'a1a6': 7,
 'a1e5': 8,
 'a1a5': 9,
 'a1d4': 10,
 'a1a4': 11,
 'a1c3': 12,
 'a1a3': 13,
 'a1b2': 14,
 'a1a2': 15,
 'a1h1': 16,
 'a1g1': 17,
 'a1f1': 18,
 'a1e1': 19,
 'a1d1': 20,
 'a1c1': 21,
 'a1b1': 22,
 'a2g8': 23,
 'a2a8': 24,
 'a2f7': 25,
 'a2a7': 26,
 'a2e6': 27,
 'a2a6': 28,
 'a2d5': 29,
 'a2a5': 30,
 'a2c4': 31,
 'a2a4': 32,
 'a2b3': 33,
 'a2a3': 34,
 'a2h2': 35,
 'a2g2': 36,
 'a2f2': 37,
 'a2e2': 38,
 'a2d2': 39,
 'a2c2': 40,
 'a2b2': 41,
 'a2b1': 42,
 'a2a1': 43,
 'a3f8': 44,
 'a3a8': 45,
 'a3e7': 46,
 'a3a7': 47,
 'a3d6': 48,
 'a3a6': 49,
 'a3c5': 50,
 'a3a5': 51,
 'a3b4': 52,
 'a3a4': 53,
 'a3h3': 54,
 'a3g3': 55,
 'a3f3': 56,
 'a3e3': 57,
 'a3d3': 58,
 'a3c3': 59,
 'a3b3': 60,
 'a3b2': 61,
 'a3a2': 62,
 'a3c1': 63,
 'a3a1': 64,
 'a4e8': 65,
 'a4a8': 66,
 'a4d7': 67,
 'a4a7': 68,
 'a4c6': 69,
 'a4a6': 70,
 'a4b5': 71,
 'a4a5': 72,
 'a4h4': 73,
 'a4g4': 74,
 'a4f4': 75,
 'a4e4': 76,
 'a4d4': 77,
 'a4c4': 78,
 'a4b4': 79,
 'a4b3': 80,
 'a4a3': 81,
 'a4c2': 82,
 'a4a2': 83,
 'a4d1': 84,
 'a4a1': 85,
 'a5d8': 86,
 'a5a8': 87,
 'a5c7': 88,
 'a5a7': 89,
 'a5b6': 90,
 'a5a6': 91,
 'a5h5': 92,
 'a5g5': 93,
 'a5f5': 94,
 'a5e5': 95,
 'a5d5': 96,
 'a5c5': 97,
 'a5b5': 98,
 'a5b4': 99,
 'a5a4': 100,
 'a5c3': 101,
 'a5a3': 102,
 'a5d2': 103,
 'a5a2': 104,
 'a5e1': 105,
 'a5a1': 106,
 'a6c8': 107,
 'a6a8': 108,
 'a6b7': 109,
 'a6a7': 110,
 'a6h6': 111,
 'a6g6': 112,
 'a6f6': 113,
 'a6e6': 114,
 'a6d6': 115,
 'a6c6': 116,
 'a6b6': 117,
 'a6b5': 118,
 'a6a5': 119,
 'a6c4': 120,
 'a6a4': 121,
 'a6d3': 122,
 'a6a3': 123,
 'a6e2': 124,
 'a6a2': 125,
 'a6f1': 126,
 'a6a1': 127,
 'a7b8': 128,
 'a7a8': 129,
 'a7h7': 130,
 'a7g7': 131,
 'a7f7': 132,
 'a7e7': 133,
 'a7d7': 134,
 'a7c7': 135,
 'a7b7': 136,
 'a7b6': 137,
 'a7a6': 138,
 'a7c5': 139,
 'a7a5': 140,
 'a7d4': 141,
 'a7a4': 142,
 'a7e3': 143,
 'a7a3': 144,
 'a7f2': 145,
 'a7a2': 146,
 'a7g1': 147,
 'a7a1': 148,
 'a8h8': 149,
 'a8g8': 150,
 'a8f8': 151,
 'a8e8': 152,
 'a8d8': 153,
 'a8c8': 154,
 'a8b8': 155,
 'a8b7': 156,
 'a8a7': 157,
 'a8c6': 158,
 'a8a6': 159,
 'a8d5': 160,
 'a8a5': 161,
 'a8e4': 162,
 'a8a4': 163,
 'a8f3': 164,
 'a8a3': 165,
 'a8g2': 166,
 'a8a2': 167,
 'a8h1': 168,
 'a8a1': 169,
 'b1b8': 170,
 'b1h7': 171,
 'b1b7': 172,
 'b1g6': 173,
 'b1b6': 174,
 'b1f5': 175,
 'b1b5': 176,
 'b1e4': 177,
 'b1b4': 178,
 'b1d3': 179,
 'b1b3': 180,
 'b1c2': 181,
 'b1b2': 182,
 'b1a2': 183,
 'b1h1': 184,
 'b1g1': 185,
 'b1f1': 186,
 'b1e1': 187,
 'b1d1': 188,
 'b1c1': 189,
 'b1a1': 190,
 'b2h8': 191,
 'b2b8': 192,
 'b2g7': 193,
 'b2b7': 194,
 'b2f6': 195,
 'b2b6': 196,
 'b2e5': 197,
 'b2b5': 198,
 'b2d4': 199,
 'b2b4': 200,
 'b2c3': 201,
 'b2b3': 202,
 'b2a3': 203,
 'b2h2': 204,
 'b2g2': 205,
 'b2f2': 206,
 'b2e2': 207,
 'b2d2': 208,
 'b2c2': 209,
 'b2a2': 210,
 'b2c1': 211,
 'b2b1': 212,
 'b2a1': 213,
 'b3g8': 214,
 'b3b8': 215,
 'b3f7': 216,
 'b3b7': 217,
 'b3e6': 218,
 'b3b6': 219,
 'b3d5': 220,
 'b3b5': 221,
 'b3c4': 222,
 'b3b4': 223,
 'b3a4': 224,
 'b3h3': 225,
 'b3g3': 226,
 'b3f3': 227,
 'b3e3': 228,
 'b3d3': 229,
 'b3c3': 230,
 'b3a3': 231,
 'b3c2': 232,
 'b3b2': 233,
 'b3a2': 234,
 'b3d1': 235,
 'b3b1': 236,
 'b4f8': 237,
 'b4b8': 238,
 'b4e7': 239,
 'b4b7': 240,
 'b4d6': 241,
 'b4b6': 242,
 'b4c5': 243,
 'b4b5': 244,
 'b4a5': 245,
 'b4h4': 246,
 'b4g4': 247,
 'b4f4': 248,
 'b4e4': 249,
 'b4d4': 250,
 'b4c4': 251,
 'b4a4': 252,
 'b4c3': 253,
 'b4b3': 254,
 'b4a3': 255,
 'b4d2': 256,
 'b4b2': 257,
 'b4e1': 258,
 'b4b1': 259,
 'b5e8': 260,
 'b5b8': 261,
 'b5d7': 262,
 'b5b7': 263,
 'b5c6': 264,
 'b5b6': 265,
 'b5a6': 266,
 'b5h5': 267,
 'b5g5': 268,
 'b5f5': 269,
 'b5e5': 270,
 'b5d5': 271,
 'b5c5': 272,
 'b5a5': 273,
 'b5c4': 274,
 'b5b4': 275,
 'b5a4': 276,
 'b5d3': 277,
 'b5b3': 278,
 'b5e2': 279,
 'b5b2': 280,
 'b5f1': 281,
 'b5b1': 282,
 'b6d8': 283,
 'b6b8': 284,
 'b6c7': 285,
 'b6b7': 286,
 'b6a7': 287,
 'b6h6': 288,
 'b6g6': 289,
 'b6f6': 290,
 'b6e6': 291,
 'b6d6': 292,
 'b6c6': 293,
 'b6a6': 294,
 'b6c5': 295,
 'b6b5': 296,
 'b6a5': 297,
 'b6d4': 298,
 'b6b4': 299,
 'b6e3': 300,
 'b6b3': 301,
 'b6f2': 302,
 'b6b2': 303,
 'b6g1': 304,
 'b6b1': 305,
 'b7c8': 306,
 'b7b8': 307,
 'b7a8': 308,
 'b7h7': 309,
 'b7g7': 310,
 'b7f7': 311,
 'b7e7': 312,
 'b7d7': 313,
 'b7c7': 314,
 'b7a7': 315,
 'b7c6': 316,
 'b7b6': 317,
 'b7a6': 318,
 'b7d5': 319,
 'b7b5': 320,
 'b7e4': 321,
 'b7b4': 322,
 'b7f3': 323,
 'b7b3': 324,
 'b7g2': 325,
 'b7b2': 326,
 'b7h1': 327,
 'b7b1': 328,
 'b8h8': 329,
 'b8g8': 330,
 'b8f8': 331,
 'b8e8': 332,
 'b8d8': 333,
 'b8c8': 334,
 'b8a8': 335,
 'b8c7': 336,
 'b8b7': 337,
 'b8a7': 338,
 'b8d6': 339,
 'b8b6': 340,
 'b8e5': 341,
 'b8b5': 342,
 'b8f4': 343,
 'b8b4': 344,
 'b8g3': 345,
 'b8b3': 346,
 'b8h2': 347,
 'b8b2': 348,
 'b8b1': 349,
 'c1c8': 350,
 'c1c7': 351,
 'c1h6': 352,
 'c1c6': 353,
 'c1g5': 354,
 'c1c5': 355,
 'c1f4': 356,
 'c1c4': 357,
 'c1e3': 358,
 'c1c3': 359,
 'c1a3': 360,
 'c1d2': 361,
 'c1c2': 362,
 'c1b2': 363,
 'c1h1': 364,
 'c1g1': 365,
 'c1f1': 366,
 'c1e1': 367,
 'c1d1': 368,
 'c1b1': 369,
 'c1a1': 370,
 'c2c8': 371,
 'c2h7': 372,
 'c2c7': 373,
 'c2g6': 374,
 'c2c6': 375,
 'c2f5': 376,
 'c2c5': 377,
 'c2e4': 378,
 'c2c4': 379,
 'c2a4': 380,
 'c2d3': 381,
 'c2c3': 382,
 'c2b3': 383,
 'c2h2': 384,
 'c2g2': 385,
 'c2f2': 386,
 'c2e2': 387,
 'c2d2': 388,
 'c2b2': 389,
 'c2a2': 390,
 'c2d1': 391,
 'c2c1': 392,
 'c2b1': 393,
 'c3h8': 394,
 'c3c8': 395,
 'c3g7': 396,
 'c3c7': 397,
 'c3f6': 398,
 'c3c6': 399,
 'c3e5': 400,
 'c3c5': 401,
 'c3a5': 402,
 'c3d4': 403,
 'c3c4': 404,
 'c3b4': 405,
 'c3h3': 406,
 'c3g3': 407,
 'c3f3': 408,
 'c3e3': 409,
 'c3d3': 410,
 'c3b3': 411,
 'c3a3': 412,
 'c3d2': 413,
 'c3c2': 414,
 'c3b2': 415,
 'c3e1': 416,
 'c3c1': 417,
 'c3a1': 418,
 'c4g8': 419,
 'c4c8': 420,
 'c4f7': 421,
 'c4c7': 422,
 'c4e6': 423,
 'c4c6': 424,
 'c4a6': 425,
 'c4d5': 426,
 'c4c5': 427,
 'c4b5': 428,
 'c4h4': 429,
 'c4g4': 430,
 'c4f4': 431,
 'c4e4': 432,
 'c4d4': 433,
 'c4b4': 434,
 'c4a4': 435,
 'c4d3': 436,
 'c4c3': 437,
 'c4b3': 438,
 'c4e2': 439,
 'c4c2': 440,
 'c4a2': 441,
 'c4f1': 442,
 'c4c1': 443,
 'c5f8': 444,
 'c5c8': 445,
 'c5e7': 446,
 'c5c7': 447,
 'c5a7': 448,
 'c5d6': 449,
 'c5c6': 450,
 'c5b6': 451,
 'c5h5': 452,
 'c5g5': 453,
 'c5f5': 454,
 'c5e5': 455,
 'c5d5': 456,
 'c5b5': 457,
 'c5a5': 458,
 'c5d4': 459,
 'c5c4': 460,
 'c5b4': 461,
 'c5e3': 462,
 'c5c3': 463,
 'c5a3': 464,
 'c5f2': 465,
 'c5c2': 466,
 'c5g1': 467,
 'c5c1': 468,
 'c6e8': 469,
 'c6c8': 470,
 'c6a8': 471,
 'c6d7': 472,
 'c6c7': 473,
 'c6b7': 474,
 'c6h6': 475,
 'c6g6': 476,
 'c6f6': 477,
 'c6e6': 478,
 'c6d6': 479,
 'c6b6': 480,
 'c6a6': 481,
 'c6d5': 482,
 'c6c5': 483,
 'c6b5': 484,
 'c6e4': 485,
 'c6c4': 486,
 'c6a4': 487,
 'c6f3': 488,
 'c6c3': 489,
 'c6g2': 490,
 'c6c2': 491,
 'c6h1': 492,
 'c6c1': 493,
 'c7d8': 494,
 'c7c8': 495,
 'c7b8': 496,
 'c7h7': 497,
 'c7g7': 498,
 'c7f7': 499,
 'c7e7': 500,
 'c7d7': 501,
 'c7b7': 502,
 'c7a7': 503,
 'c7d6': 504,
 'c7c6': 505,
 'c7b6': 506,
 'c7e5': 507,
 'c7c5': 508,
 'c7a5': 509,
 'c7f4': 510,
 'c7c4': 511,
 'c7g3': 512,
 'c7c3': 513,
 'c7h2': 514,
 'c7c2': 515,
 'c7c1': 516,
 'c8h8': 517,
 'c8g8': 518,
 'c8f8': 519,
 'c8e8': 520,
 'c8d8': 521,
 'c8b8': 522,
 'c8a8': 523,
 'c8d7': 524,
 'c8c7': 525,
 'c8b7': 526,
 'c8e6': 527,
 'c8c6': 528,
 'c8a6': 529,
 'c8f5': 530,
 'c8c5': 531,
 'c8g4': 532,
 'c8c4': 533,
 'c8h3': 534,
 'c8c3': 535,
 'c8c2': 536,
 'c8c1': 537,
 'd1d8': 538,
 'd1d7': 539,
 'd1d6': 540,
 'd1h5': 541,
 'd1d5': 542,
 'd1g4': 543,
 'd1d4': 544,
 'd1a4': 545,
 'd1f3': 546,
 'd1d3': 547,
 'd1b3': 548,
 'd1e2': 549,
 'd1d2': 550,
 'd1c2': 551,
 'd1h1': 552,
 'd1g1': 553,
 'd1f1': 554,
 'd1e1': 555,
 'd1c1': 556,
 'd1b1': 557,
 'd1a1': 558,
 'd2d8': 559,
 'd2d7': 560,
 'd2h6': 561,
 'd2d6': 562,
 'd2g5': 563,
 'd2d5': 564,
 'd2a5': 565,
 'd2f4': 566,
 'd2d4': 567,
 'd2b4': 568,
 'd2e3': 569,
 'd2d3': 570,
 'd2c3': 571,
 'd2h2': 572,
 'd2g2': 573,
 'd2f2': 574,
 'd2e2': 575,
 'd2c2': 576,
 'd2b2': 577,
 'd2a2': 578,
 'd2e1': 579,
 'd2d1': 580,
 'd2c1': 581,
 'd3d8': 582,
 'd3h7': 583,
 'd3d7': 584,
 'd3g6': 585,
 'd3d6': 586,
 'd3a6': 587,
 'd3f5': 588,
 'd3d5': 589,
 'd3b5': 590,
 'd3e4': 591,
 'd3d4': 592,
 'd3c4': 593,
 'd3h3': 594,
 'd3g3': 595,
 'd3f3': 596,
 'd3e3': 597,
 'd3c3': 598,
 'd3b3': 599,
 'd3a3': 600,
 'd3e2': 601,
 'd3d2': 602,
 'd3c2': 603,
 'd3f1': 604,
 'd3d1': 605,
 'd3b1': 606,
 'd4h8': 607,
 'd4d8': 608,
 'd4g7': 609,
 'd4d7': 610,
 'd4a7': 611,
 'd4f6': 612,
 'd4d6': 613,
 'd4b6': 614,
 'd4e5': 615,
 'd4d5': 616,
 'd4c5': 617,
 'd4h4': 618,
 'd4g4': 619,
 'd4f4': 620,
 'd4e4': 621,
 'd4c4': 622,
 'd4b4': 623,
 'd4a4': 624,
 'd4e3': 625,
 'd4d3': 626,
 'd4c3': 627,
 'd4f2': 628,
 'd4d2': 629,
 'd4b2': 630,
 'd4g1': 631,
 'd4d1': 632,
 'd4a1': 633,
 'd5g8': 634,
 'd5d8': 635,
 'd5a8': 636,
 'd5f7': 637,
 'd5d7': 638,
 'd5b7': 639,
 'd5e6': 640,
 'd5d6': 641,
 'd5c6': 642,
 'd5h5': 643,
 'd5g5': 644,
 'd5f5': 645,
 'd5e5': 646,
 'd5c5': 647,
 'd5b5': 648,
 'd5a5': 649,
 'd5e4': 650,
 'd5d4': 651,
 'd5c4': 652,
 'd5f3': 653,
 'd5d3': 654,
 'd5b3': 655,
 'd5g2': 656,
 'd5d2': 657,
 'd5a2': 658,
 'd5h1': 659,
 'd5d1': 660,
 'd6f8': 661,
 'd6d8': 662,
 'd6b8': 663,
 'd6e7': 664,
 'd6d7': 665,
 'd6c7': 666,
 'd6h6': 667,
 'd6g6': 668,
 'd6f6': 669,
 'd6e6': 670,
 'd6c6': 671,
 'd6b6': 672,
 'd6a6': 673,
 'd6e5': 674,
 'd6d5': 675,
 'd6c5': 676,
 'd6f4': 677,
 'd6d4': 678,
 'd6b4': 679,
 'd6g3': 680,
 'd6d3': 681,
 'd6a3': 682,
 'd6h2': 683,
 'd6d2': 684,
 'd6d1': 685,
 'd7e8': 686,
 'd7d8': 687,
 'd7c8': 688,
 'd7h7': 689,
 'd7g7': 690,
 'd7f7': 691,
 'd7e7': 692,
 'd7c7': 693,
 'd7b7': 694,
 'd7a7': 695,
 'd7e6': 696,
 'd7d6': 697,
 'd7c6': 698,
 'd7f5': 699,
 'd7d5': 700,
 'd7b5': 701,
 'd7g4': 702,
 'd7d4': 703,
 'd7a4': 704,
 'd7h3': 705,
 'd7d3': 706,
 'd7d2': 707,
 'd7d1': 708,
 'd8h8': 709,
 'd8g8': 710,
 'd8f8': 711,
 'd8e8': 712,
 'd8c8': 713,
 'd8b8': 714,
 'd8a8': 715,
 'd8e7': 716,
 'd8d7': 717,
 'd8c7': 718,
 'd8f6': 719,
 'd8d6': 720,
 'd8b6': 721,
 'd8g5': 722,
 'd8d5': 723,
 'd8a5': 724,
 'd8h4': 725,
 'd8d4': 726,
 'd8d3': 727,
 'd8d2': 728,
 'd8d1': 729,
 'e1e8': 730,
 'e1e7': 731,
 'e1e6': 732,
 'e1e5': 733,
 'e1a5': 734,
 'e1h4': 735,
 'e1e4': 736,
 'e1b4': 737,
 'e1g3': 738,
 'e1e3': 739,
 'e1c3': 740,
 'e1f2': 741,
 'e1e2': 742,
 'e1d2': 743,
 'e1h1': 744,
 'e1g1': 745,
 'e1f1': 746,
 'e1d1': 747,
 'e1c1': 748,
 'e1b1': 749,
 'e1a1': 750,
 'e2e8': 751,
 'e2e7': 752,
 'e2e6': 753,
 'e2a6': 754,
 'e2h5': 755,
 'e2e5': 756,
 'e2b5': 757,
 'e2g4': 758,
 'e2e4': 759,
 'e2c4': 760,
 'e2f3': 761,
 'e2e3': 762,
 'e2d3': 763,
 'e2h2': 764,
 'e2g2': 765,
 'e2f2': 766,
 'e2d2': 767,
 'e2c2': 768,
 'e2b2': 769,
 'e2a2': 770,
 'e2f1': 771,
 'e2e1': 772,
 'e2d1': 773,
 'e3e8': 774,
 'e3e7': 775,
 'e3a7': 776,
 'e3h6': 777,
 'e3e6': 778,
 'e3b6': 779,
 'e3g5': 780,
 'e3e5': 781,
 'e3c5': 782,
 'e3f4': 783,
 'e3e4': 784,
 'e3d4': 785,
 'e3h3': 786,
 'e3g3': 787,
 'e3f3': 788,
 'e3d3': 789,
 'e3c3': 790,
 'e3b3': 791,
 'e3a3': 792,
 'e3f2': 793,
 'e3e2': 794,
 'e3d2': 795,
 'e3g1': 796,
 'e3e1': 797,
 'e3c1': 798,
 'e4e8': 799,
 'e4a8': 800,
 'e4h7': 801,
 'e4e7': 802,
 'e4b7': 803,
 'e4g6': 804,
 'e4e6': 805,
 'e4c6': 806,
 'e4f5': 807,
 'e4e5': 808,
 'e4d5': 809,
 'e4h4': 810,
 'e4g4': 811,
 'e4f4': 812,
 'e4d4': 813,
 'e4c4': 814,
 'e4b4': 815,
 'e4a4': 816,
 'e4f3': 817,
 'e4e3': 818,
 'e4d3': 819,
 'e4g2': 820,
 'e4e2': 821,
 'e4c2': 822,
 'e4h1': 823,
 'e4e1': 824,
 'e4b1': 825,
 'e5h8': 826,
 'e5e8': 827,
 'e5b8': 828,
 'e5g7': 829,
 'e5e7': 830,
 'e5c7': 831,
 'e5f6': 832,
 'e5e6': 833,
 'e5d6': 834,
 'e5h5': 835,
 'e5g5': 836,
 'e5f5': 837,
 'e5d5': 838,
 'e5c5': 839,
 'e5b5': 840,
 'e5a5': 841,
 'e5f4': 842,
 'e5e4': 843,
 'e5d4': 844,
 'e5g3': 845,
 'e5e3': 846,
 'e5c3': 847,
 'e5h2': 848,
 'e5e2': 849,
 'e5b2': 850,
 'e5e1': 851,
 'e5a1': 852,
 'e6g8': 853,
 'e6e8': 854,
 'e6c8': 855,
 'e6f7': 856,
 'e6e7': 857,
 'e6d7': 858,
 'e6h6': 859,
 'e6g6': 860,
 'e6f6': 861,
 'e6d6': 862,
 'e6c6': 863,
 'e6b6': 864,
 'e6a6': 865,
 'e6f5': 866,
 'e6e5': 867,
 'e6d5': 868,
 'e6g4': 869,
 'e6e4': 870,
 'e6c4': 871,
 'e6h3': 872,
 'e6e3': 873,
 'e6b3': 874,
 'e6e2': 875,
 'e6a2': 876,
 'e6e1': 877,
 'e7f8': 878,
 'e7e8': 879,
 'e7d8': 880,
 'e7h7': 881,
 'e7g7': 882,
 'e7f7': 883,
 'e7d7': 884,
 'e7c7': 885,
 'e7b7': 886,
 'e7a7': 887,
 'e7f6': 888,
 'e7e6': 889,
 'e7d6': 890,
 'e7g5': 891,
 'e7e5': 892,
 'e7c5': 893,
 'e7h4': 894,
 'e7e4': 895,
 'e7b4': 896,
 'e7e3': 897,
 'e7a3': 898,
 'e7e2': 899,
 'e7e1': 900,
 'e8h8': 901,
 'e8g8': 902,
 'e8f8': 903,
 'e8d8': 904,
 'e8c8': 905,
 'e8b8': 906,
 'e8a8': 907,
 'e8f7': 908,
 'e8e7': 909,
 'e8d7': 910,
 'e8g6': 911,
 'e8e6': 912,
 'e8c6': 913,
 'e8h5': 914,
 'e8e5': 915,
 'e8b5': 916,
 'e8e4': 917,
 'e8a4': 918,
 'e8e3': 919,
 'e8e2': 920,
 'e8e1': 921,
 'f1f8': 922,
 'f1f7': 923,
 'f1f6': 924,
 'f1a6': 925,
 'f1f5': 926,
 'f1b5': 927,
 'f1f4': 928,
 'f1c4': 929,
 'f1h3': 930,
 'f1f3': 931,
 'f1d3': 932,
 'f1g2': 933,
 'f1f2': 934,
 'f1e2': 935,
 'f1h1': 936,
 'f1g1': 937,
 'f1e1': 938,
 'f1d1': 939,
 'f1c1': 940,
 'f1b1': 941,
 'f1a1': 942,
 'f2f8': 943,
 'f2f7': 944,
 'f2a7': 945,
 'f2f6': 946,
 'f2b6': 947,
 'f2f5': 948,
 'f2c5': 949,
 'f2h4': 950,
 'f2f4': 951,
 'f2d4': 952,
 'f2g3': 953,
 'f2f3': 954,
 'f2e3': 955,
 'f2h2': 956,
 'f2g2': 957,
 'f2e2': 958,
 'f2d2': 959,
 'f2c2': 960,
 'f2b2': 961,
 'f2a2': 962,
 'f2g1': 963,
 'f2f1': 964,
 'f2e1': 965,
 'f3f8': 966,
 'f3a8': 967,
 'f3f7': 968,
 'f3b7': 969,
 'f3f6': 970,
 'f3c6': 971,
 'f3h5': 972,
 'f3f5': 973,
 'f3d5': 974,
 'f3g4': 975,
 'f3f4': 976,
 'f3e4': 977,
 'f3h3': 978,
 'f3g3': 979,
 'f3e3': 980,
 'f3d3': 981,
 'f3c3': 982,
 'f3b3': 983,
 'f3a3': 984,
 'f3g2': 985,
 'f3f2': 986,
 'f3e2': 987,
 'f3h1': 988,
 'f3f1': 989,
 'f3d1': 990,
 'f4f8': 991,
 'f4b8': 992,
 'f4f7': 993,
 'f4c7': 994,
 'f4h6': 995,
 'f4f6': 996,
 'f4d6': 997,
 'f4g5': 998,
 'f4f5': 999,
 'f4e5': 1000,
 'f4h4': 1001,
 ...}